/**
 * Node-native port of utils/doodleGenerator.ts + the Replicate/Appwrite
 * Storage steps in core/agents/MainAgent.ts's runAgentWorkflow. The browser
 * version base64-decodes into a Blob/File (browser-only APIs); this version
 * works directly with a Node Buffer and node-appwrite's InputFile.
 */

import { InputFile } from 'node-appwrite/file';
import { storageServer, serverConfig, ID } from '../lib/appwriteServer';

const REPLICATE_ENDPOINT = 'https://api.replicate.com/v1/models/black-forest-labs/flux-schnell/predictions';

const generateOnce = async (
    prompt: string,
    aspectRatio: string,
    seed?: number
): Promise<{ imageUrl: string; buffer: Buffer }> => {
    const token = process.env.REPLICATE_API_TOKEN;
    if (!token) throw new Error('Missing REPLICATE_API_TOKEN');

    const response = await fetch(REPLICATE_ENDPOINT, {
        method: 'POST',
        headers: {
            'Authorization': `Token ${token}`,
            'Content-Type': 'application/json',
            'Prefer': 'wait',
        },
        body: JSON.stringify({
            input: {
                prompt,
                go_fast: true,
                megapixels: '1',
                num_outputs: 1,
                aspect_ratio: aspectRatio,
                output_format: 'webp',
                output_quality: 90,
                num_inference_steps: 4,
                // Locking seed enforces visual style consistency: same line weight,
                // stroke confidence, and compositional density across all slides
                // in the same carousel job.
                ...(seed !== undefined ? { seed } : {}),
            },
        }),
    });

    if (!response.ok) {
        const errText = await response.text();
        const err: any = new Error(`Replicate error: ${errText}`);
        err.status = response.status;
        err.body = errText;
        throw err;
    }

    const prediction = await response.json();
    const imageUrl = prediction.output?.[0];
    if (!imageUrl) throw new Error('No image generated by Replicate');

    // replicate.delivery sends no CORS headers to browsers, but the worker is
    // server-to-server here so a plain fetch works fine.
    const imgResp = await fetch(imageUrl);
    const buffer = Buffer.from(await imgResp.arrayBuffer());

    return { imageUrl, buffer };
};

const generateWithRetry = async (
    prompt: string,
    aspectRatio: string,
    seed?: number,
    maxAttempts = 5
): Promise<{ imageUrl: string; buffer: Buffer }> => {
    for (let attempt = 1; ; attempt++) {
        try {
            return await generateOnce(prompt, aspectRatio, seed);
        } catch (err: any) {
            const msg = String(err?.body || err?.message || err);
            const throttled = err?.status === 429 || msg.includes('429') || msg.includes('throttled');
            if (!throttled || attempt >= maxAttempts) throw err;

            const retryMatch = msg.match(/retry_after"?:\s*(\d+)/);
            const waitSeconds = (retryMatch ? parseInt(retryMatch[1], 10) : 10) + 2;
            console.warn(`[doodleGen] Replicate throttled (attempt ${attempt}/${maxAttempts}), retrying in ${waitSeconds}s...`);
            await new Promise(r => setTimeout(r, waitSeconds * 1000));
        }
    }
};

/** Generates a doodle and persists it to Appwrite Storage; returns the durable view URL. */
export const generateAndPersistDoodle = async (
    prompt: string,
    aspectRatio: string = '2:3',
    seed?: number
): Promise<string> => {
    const { imageUrl, buffer } = await generateWithRetry(prompt, aspectRatio, seed);

    if (!serverConfig.storageBucketId) {
        console.warn('[doodleGen] Missing storage bucket config — returning ephemeral Replicate URL');
        return imageUrl;
    }

    try {
        const file = InputFile.fromBuffer(buffer, `doodle-${ID.unique()}.webp`);
        const uploaded = await storageServer.createFile(serverConfig.storageBucketId, ID.unique(), file);
        // node-appwrite's Storage.getFileView() downloads the bytes (server SDK
        // semantics differ from the browser SDK) — build the public view URL directly.
        return `${serverConfig.endpoint}/storage/buckets/${serverConfig.storageBucketId}/files/${uploaded.$id}/view?project=${serverConfig.projectId}`;
    } catch (persistErr) {
        console.error('[doodleGen] Upload failed, using ephemeral URL:', persistErr);
        return imageUrl;
    }
};
